In [1]:
import numpy as np
import scipy.io
import meshplot as mp
import igl
import meshio
import h5py
from shapely.geometry import Polygon, Point

import sys
sys.path.append('./ShellUtils')
%load_ext autoreload
%autoreload 2
import Gen, TriMesh, Visual, Geometry

In [22]:
# read re-analysis H5 file
with h5py.File('/Users/ziyizhang/Projects/Zebrafish/data/ctrl_em1_filter-analysis-02_18T09_59-AnalysisInput.h5', 'r+') as f:
    print("Keys: %s" % f.keys())

    V = f['V'].value[()]
    F = f['F'].value[()]
    frames = f['frames'].value[()]
    Nverts = f['Nverts'].value[()]
    VV = np.zeros((frames, Nverts, 3))
    for i in range(frames):
        VV[i, :, :] = V[i*Nverts:(i+1)*Nverts, :]

Keys: <KeysViewHDF5 ['E', 'F', 'Nverts', 'V', 'discr_order', 'frames', 'imgCols', 'imgRows', 'is_linear', 'layerPerImg', 'markerRCMap_mat', 'max_tet_vol', 'n_refs', 'nu', 'offset', 'radius_edge_ratio', 'resolutionX', 'resolutionY', 'resolutionZ', 'upsample', 'vismesh_rel_area']>


In [18]:
# re-store global displacement

array([252.33082073, 252.2895558 ,  23.61444444])

In [28]:
meanL = np.array([igl.avg_edge_length(np.squeeze(VV[f, :, :]), F) for f in range(frames)])

In [31]:
F.shape

(302, 3)

In [27]:
tt = np.squeeze(VV[1, :, :])
mp.plot(tt, F, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(158.26949…

In [115]:
# Read debug msh
with h5py.File('/Users/ziyizhang/Projects/Zebrafish/release/test.h5', 'r+') as f:
    print("Keys: %s" % f.keys())
    T = f['T'].value[()]
    V = f['V'].value[()]

    bm_v = f['bm_v'].value[()] 
    bm_f = f['bm_f'].value[()] 
    Tid = f['Tid'].value[()]
    result_f = f['result_f'].value[()]

Keys: <KeysViewHDF5 ['T', 'Tid', 'V', 'bm_f', 'bm_v', 'result_f']>


In [107]:
# clip
z_min = 1
z_max = 20

plt = mp.plot(V, bm_f, shading={"wireframe": True})
V_clip = np.array([V[i, 2] > z_min and V[i, 2] < z_max for i in range(V.shape[0])])
T_clip = T[np.array([V_clip[T[i, 0]] and V_clip[T[i, 1]] and V_clip[T[i, 2]] and V_clip[T[i, 3]] for i in range(T.shape[0])])]
plt.add_edges(V, Geometry.t2e(T_clip))
plt.add_edges(bm_v, Geometry.f2e(bm_f), shading={"line_color": "red"})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(51.708511…

2

In [113]:
print(Tid.shape)
Tid_unique, count = np.unique(Tid, return_counts=True)
print(Tid_unique.shape)
Tid_unique[count > 1]

(1026,)
(1025,)


array([4595], dtype=int32)

In [117]:
T_boundary = igl.boundary_facets(T)
components = igl.face_components(T_boundary)
print(components.max() + 1)

plt = mp.plot(V, bm_f, shading={"wireframe": True})
#plt = mp.plot(V, Geometry.t2e(T[Tid, :]), shading={"wireframe": True})
plt.add_edges(V, Geometry.t2e(T[Tid]), shading={"line_color": "blue"})
plt.add_edges(V, Geometry.f2e(bm_f), shading={"line_color": "black"})
# plt.add_points(V[[129], :], shading={"point_color": "red", "point_size": 5})

plt.add_points(V[[678]], shading={"point_color": "red", "point_size": 5})
plt.add_points(V[[708]], shading={"point_color": "blue", "point_size": 5})


1


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(51.708511…

3

In [87]:
t_with_129 = np.where(np.any(T[Tid] == 129, axis = 1)) 

In [95]:
T[Tid] == 129

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
T[Tid][t_with_129]

array([[ 149,  138,  141,  129],
       [ 149,  138,  141,  129],
       [ 149,  138,  141,  129],
       [ 138,  124,  129, 1679],
       [ 141,  149,  129, 1679],
       [ 149,  138,  129, 1679],
       [ 129,  117,  125, 1923],
       [ 129,  109,  117, 1923],
       [ 141,  129,  125, 1923],
       [ 109,  129,  124, 2048]], dtype=int32)

In [91]:
np.unique(Tid).shape

(303,)

In [94]:
plt = mp.plot(V, Geometry.t2e(T[Tid][t_with_129]), shading={"wireframe": "true", "line_color": "red"})
plt.add_edges(V, Geometry.f2e(bm_f))

plt.add_points(V[np.array([149, 138, 141, 129])], shading={"point_color": "red", "point_size": 5})
plt.add_points(V[np.array([1679])], shading={"point_color": "blue", "point_size": 5})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(33.910924…

3

In [78]:
TTid = T[Tid]

In [44]:
Tid_array = T[Tid].flatten()

In [48]:
Tid_array = np.sort(Tid_array)

In [54]:
bmid_array = bm_f.flatten()
bmid_array = np.sort(bmid_array)

In [62]:
np.where( bmid_array-Tid_array[0:906] != 0 )

(array([675, 676, 677, 678, 681, 682, 683, 684, 685, 686, 689, 690, 691,
        692, 695, 696, 697, 698, 701, 702, 703, 704, 707, 708, 709, 710,
        713, 714, 715, 716, 719, 720, 721, 722, 725, 726, 727, 728, 729,
        730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742,
        743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755,
        756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768,
        769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781,
        782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794,
        795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807,
        808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820,
        821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833,
        834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846,
        847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859,
        860, 861, 862, 863, 864, 865, 866, 867, 868

In [63]:
bmid_array[675]

130

In [56]:
bmid_array

array([  0,   0,   1,   1,   1,   2,   2,   2,   3,   3,   3,   4,   4,
         5,   5,   6,   6,   7,   7,   8,   9,   9,   9,  10,  10,  10,
        10,  10,  10,  11,  11,  12,  12,  12,  12,  12,  12,  13,  13,
        13,  13,  13,  13,  14,  14,  14,  14,  14,  14,  15,  15,  15,
        15,  16,  16,  16,  16,  17,  17,  17,  17,  18,  18,  18,  18,
        18,  18,  19,  19,  19,  19,  20,  20,  20,  20,  21,  21,  21,
        21,  21,  21,  22,  22,  22,  22,  22,  22,  23,  23,  23,  23,
        23,  23,  24,  24,  24,  24,  24,  24,  25,  25,  25,  25,  25,
        25,  26,  26,  26,  26,  26,  26,  27,  27,  27,  27,  28,  28,
        28,  28,  28,  28,  29,  29,  29,  29,  29,  29,  30,  30,  30,
        30,  30,  30,  31,  31,  31,  31,  31,  31,  32,  32,  33,  33,
        33,  33,  33,  33,  34,  34,  34,  34,  34,  34,  35,  35,  35,
        35,  35,  35,  36,  36,  36,  36,  36,  36,  37,  37,  38,  38,
        38,  38,  38,  38,  39,  39,  39,  39,  39,  39,  40,  4

In [59]:
np.squeeze(Tid_array[0:906])

array([  0,   0,   1,   1,   1,   2,   2,   2,   3,   3,   3,   4,   4,
         5,   5,   6,   6,   7,   7,   8,   9,   9,   9,  10,  10,  10,
        10,  10,  10,  11,  11,  12,  12,  12,  12,  12,  12,  13,  13,
        13,  13,  13,  13,  14,  14,  14,  14,  14,  14,  15,  15,  15,
        15,  16,  16,  16,  16,  17,  17,  17,  17,  18,  18,  18,  18,
        18,  18,  19,  19,  19,  19,  20,  20,  20,  20,  21,  21,  21,
        21,  21,  21,  22,  22,  22,  22,  22,  22,  23,  23,  23,  23,
        23,  23,  24,  24,  24,  24,  24,  24,  25,  25,  25,  25,  25,
        25,  26,  26,  26,  26,  26,  26,  27,  27,  27,  27,  28,  28,
        28,  28,  28,  28,  29,  29,  29,  29,  29,  29,  30,  30,  30,
        30,  30,  30,  31,  31,  31,  31,  31,  31,  32,  32,  33,  33,
        33,  33,  33,  33,  34,  34,  34,  34,  34,  34,  35,  35,  35,
        35,  35,  35,  36,  36,  36,  36,  36,  36,  37,  37,  38,  38,
        38,  38,  38,  38,  39,  39,  39,  39,  39,  39,  40,  4

In [12]:
f = h5py.File('/Users/ziyizhang/Projects/Zebrafish/data/em5_19nov2020-3-1-analysis-02_15T02_04-AnalysisInput.h5', 'r+')
print("Keys: %s" % f.keys())
E = f['E'].value[()]
F = f['F'].value[()]
Nverts = f['Nverts'].value[()]
V = f['V'].value[()]
discr_order = f['discr_order'].value[()]
frames = f['frames'].value[()]
markerRCMap_mat = f['markerRCMap_mat'].value[()]

Keys: <KeysViewHDF5 ['E', 'F', 'Nverts', 'V', 'discr_order', 'frames', 'is_linear', 'markerRCMap_mat', 'max_tet_vol', 'n_refs', 'nu', 'offset', 'radius_edge_ratio', 'upsample', 'vismesh_rel_area']>


In [14]:
plt = mp.plot(shell_top, Geometry.f2e(F_h5), shading={"wireframe": True})
plt.add_edges(shell_base, Geometry.f2e(F_h5))
#plt.add_mesh(shell_top, Geometry.f2e(F_h5))

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4995164…

1

In [ ]:
scipy.io.savemat('./MatlabScripts/length.mat', mdict={'mat': lengthMat})

In [ ]:
# Gen cube test ply
V_cube, F_cube = Gen.GenCubeObj()
igl.write_triangle_mesh("./data/dualShell_cube.ply", V_cube, F_cube, False)

In [ ]:
# dualShell_test
Vraw1 = np.array([[1, 1, 1], [2, 1, 1], [1, 2, 1]])
Vraw2 = np.array([[1, 1, 2], [2, 1, 2], [1, 2, 2]])
Vraw3 = np.array([[1, 1, 3], [3, 1, 3], [1, 3, 3]])
Vraw4 = np.array([[1, 1, 4], [3, 1, 4], [1, 3, 4]])
Fraw = np.array([[0, 1, 2]])
V_shell = np.concatenate((Vraw1, Vraw2), axis=0)
V_shell = np.concatenate((V_shell, Vraw3), axis=0)
V_shell = np.concatenate((V_shell, Vraw4), axis=0)

randTransMat = np.array([[-0.700390490817757,  -0.150045418195264,  -0.697810527901858],
                         [-0.114407726497277,  -0.941413431486692,   0.317256399674106],
                         [-0.704531072763853,   0.302038281505938,   0.642190660174339]])
V_shell = randTransMat.dot(V_shell.transpose()).transpose()

F_shell = np.concatenate((Fraw, Fraw+Vraw1.shape[0]), axis=0)
F_shell = np.concatenate((F_shell, Fraw+2*Vraw1.shape[0]), axis=0)
F_shell = np.concatenate((F_shell, Fraw+3*Vraw1.shape[0]), axis=0)

In [281]:
# Load processed mesh
# mesh = meshio.read('./dataset/51509.stl.h5_.msh')
# mesh = meshio.read('./dataset/log/log_Dec_26_1000/data/128483.stl.h5_.msh')
# mesh = meshio.read('./dataset/log/log_Dec_27_1000/data/62286.stl.h5_.msh')
# mesh = meshio.read('./dataset/log/log_Dec_28_1000/data/611675.stl.h5_.msh')
# mesh = meshio.read('./dataset/log/log_Dec_28_1000/data/77918.stl.h5_.msh')
# mesh = meshio.read('./dataset/log/log_Dec_28_1000/data/109130.stl.h5_.msh')
# mesh = meshio.read('./dataset/tetgen_result.msh')
# mesh = meshio.read('dataset/cube_2_5.obj.h5_col6.h_.msh')
mesh = meshio.read('dataset/main_linkage_arm_6a_scaled_unpositioned_back_1.hh.sat.obj.h5_col9.h_.msh')
# mesh = meshio.read('./data/dualShell_cube_.msh')
V_msh = mesh.points
T_msh = mesh.cells[0][1]
#energy = mesh.cell_data_dict['slim_energy']['tetra']
 # label = mesh.cell_data['label'][0]

In [278]:
mp.plot(V_msh, Geometry.t2e(T_msh), shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4806083…

In [282]:
T_boundary = igl.boundary_facets(T_msh)
components = igl.face_components(T_boundary)
print(components.max() + 1)
plt = mp.plot(V_msh, T_boundary[(components == 3), :], shading={"wireframe": True})
plt.add_edges(V_msh, Geometry.f2e(T_boundary[(components == 1) | True, :]), shading={"wireframe": True})

#v = np.array([[-1.6, 1.6, -1.6], [1.6, 1.6, -1.6], [1.6, 1.6, 1.6], [-0.49459213746493375, 1.7758694311449574, 0.39867713464991789], [2.1117691453623983, 2.1117691453623983, -2.1117691453623983]])
#plt.add_mesh(v, (np.array([[0, 1, 2, 3], [0, 1, 2, 4]])), shading={"wireframe": True})

3


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0784776…

1

In [123]:
print(np.nonzero(energy > 10000))
print(np.where(np.abs(energy - 18885) < 3))
print(energy[10235])
print(energy[10236])
print(T_msh[804, :])
print(T_msh[10235, :])
print(T_msh[10236, :])

(array([  804,  1462, 23890, 24570, 24579, 24590, 26788]),)
(array([804]),)
3.677912673797336
3.5763655151388956
[2323 2318 2304 6771]
[4232 4385 4371 4370]
[4232 4371 4385 4386]


In [291]:
len(str)

4930

In [211]:
V_in, F_in = igl.read_triangle_mesh('/Users/ziyizhang/Projects/ShellMesh/dataset/thin_wall_1.hh.sat.obj.h5.ply')
print(V_in.shape)
print(F_in.shape)
print(F_in.max())

(921, 3)
(1838, 3)
920


In [196]:
F_in[984, :]

array([ 61, 168, 683], dtype=int64)

In [198]:
a = igl.doublearea(V_in, F_in)

In [252]:
print(np.max(igl.face_components(F_in)))
igl.boundary_facets(F_in)

0


array([], shape=(0, 2), dtype=int64)

In [246]:
print(V_in.shape)
print(V_msh.shape)
print(F_in.shape)
print(F_boundary.shape)

(583, 3)
(1818, 3)
(1198, 3)
(3602, 3)


In [223]:
F_boundary = igl.boundary_facets(T_msh)
print(np.unique(F_boundary))
vidx = np.setdiff1d(np.arange(1794), np.unique(F_boundary))
print(vidx)

[   0    1    2 ... 1790 1791 1793]
[1792]


In [248]:
np.max(F_in)

582

In [249]:
plt = mp.plot(V_in, Geometry.f2e(F_in), shading={"wireframe": True})
#plt = mp.plot(V_msh, Geometry.f2e(F_boundary))
#plt = mp.plot(V_msh, T_msh, shading={"wireframe": True})
#plt.add_points(V_msh[[1793], :], shading={"point_size": 0.01})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0628409…

In [182]:
tt = np.arange(1400)
vidx = np.setdiff1d(tt, np.unique(F))

In [255]:
mp.plot(V_msh, Geometry.t2e(T_msh))

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.5112514…

In [205]:
plt = mp.plot(V_msh, Geometry.f2e(F_in), shading={"wireframe": True})
plt.add_points(V_in[vidx, :], shading={"point_size": 0.01, "point_color": "green"})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4999849…

1

In [154]:
# Bad tets
T_msh_bad = T_msh[:, :]
#T_msh_bad = T_msh[[804], :]
print("#bad_tets = {}".format(T_msh_bad.shape[0]))
vol = igl.volume(V_msh, T_msh_bad)
plt = mp.plot(V_msh, T_msh_bad, shading={"wireframe": True})


plt.add_points(V_msh[[T_msh_bad[0, 0]], :], shading={"point_size": 0.01, "point_color": "green"})
plt.add_points(V_msh[[T_msh_bad[0, 1]], :], shading={"point_size": 0.01, "point_color": "yellow"})
plt.add_points(V_msh[[T_msh_bad[0, 2]], :], shading={"point_size": 0.01, "point_color": "black"})
plt.add_points(V_msh[[T_msh_bad[0, 3]], :], shading={"point_size": 0.01})  # red

# Add input shell
V_in, F_in = igl.read_triangle_mesh('/Users/ziyizhang/Projects/ShellMesh/dataset/109130.stl.h5.ply')
B0, B1, T1, T0 = np.split(V_in, 4)
plt.add_lines(B1[Geometry.f2e(F_in)[:, 0]], B1[Geometry.f2e(F_in)[:, 1]], shading={"line_color": "red"})
#plt.add_lines(B0[Geometry.f2e(F_in)[:, 0]], B0[Geometry.f2e(F_in)[:, 1]], shading={"line_color": "red"})
plt.add_lines(T1[Geometry.f2e(F_in)[:, 0]], T1[Geometry.f2e(F_in)[:, 1]], shading={"line_color": "blue"})
#plt.add_mesh(T1, F_in)
#plt.add_edges(B0, Geometry.f2e(F_in), shading={"wireframe": True})
#plt.add_edges(B1, Geometry.f2e(F_in), shading={"wireframe": True})


#bad_tets = 5295


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4999849…

6

In [100]:
# Plot one-ring of a vert
V, F = igl.read_triangle_mesh('/Users/ziyizhang/Projects/ShellMesh/dataset/611675.stl.h5.ply')
B0, B1, T1, T0 = np.split(V, 4)
V1, T1 = igl.read_msh('./dataset/log/log_Dec_28_1000/data/611675.stl.h5_.msh')
targetVert = 2707
partT = T1[ np.where(T1==targetVert)[0] ]
print("#tets = {}".format(partT.shape[0]))

plt = mp.plot(V1, Geometry.t2e(partT))
#plt.add_points(V1[[targetVert]])
plt.add_points(V_msh[[T_msh_bad[0, 0]], :], shading={"point_size": 0.01, "point_color": "green"})
plt.add_points(V_msh[[T_msh_bad[0, 1]], :], shading={"point_size": 0.01, "point_color": "yellow"})
plt.add_points(V_msh[[T_msh_bad[0, 2]], :], shading={"point_size": 0.01, "point_color": "black"})
plt.add_points(V_msh[[T_msh_bad[0, 3]], :], shading={"point_size": 0.01})  # red

#tets = 13


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.8276747…

4

In [287]:
min(1, 2)

1

In [ ]:
V2 = V1.copy()
V2[11128] = V2[872]
p = mp.plot(V2, Geometry.t2e(partT), wireframe=True)
p.add_points(V2[[11128,872]], point_size=0.02)
p.add_edges(V2, Geometry.f2e(igl.boundary_facets(partT)), line_color='red')
np.linalg.norm(V1[np.unique(partT)] - V1[[11128]],axis=1)[:-1].argmin()
igl.volume(V2, partT)
partT[partT==11128] = 872
igl.volume(V2,np.array([t for t in partT if len(set(t)) ==4]))

In [ ]:
# torch
import torch as th

thV = th.from_numpy(V1)
thV.requires_grad_()
x = tw_mips3d(thV, th.from_numpy(partT))
x.sum().backward()
V2 = V1.copy()
V2[11128] -= 1e-20*thV.grad[11128].numpy()
(tw_mips3d(V2,partT)).sum()
(tw_mips3d(V1,partT)).sum()
igl.volume(V2, partT).min()
igl.volume(V1, partT).min()


def mips3d(V, T):
    from numpy import sqrt
    Jacs = V[T[:,1:]]-V[T[:,:1]]
    invstd = th.from_numpy(np.linalg.inv(np.array([[1,0,0],[0.5,sqrt(3)/2.,0],[0.5,sqrt(3)/6.,sqrt(2)/sqrt(3)]])))
    Jacs = invstd@Jacs
    frob = th.sum(Jacs**2,axis=1).sum(axis=1)
    #invfrob = th.sum(th.inverse(Jacs))
    dets = th.det(Jacs)
    return frob/dets**(2/3)

In [ ]:
V_in, F_in = igl.read_triangle_mesh('/Users/ziyizhang/Projects/ShellMesh/dataset/51509.stl.h5.ply')
plt = mp.plot(V_msh, T_msh[energy > 500, :], c = np.ones(3)/2, shading={"wireframe": True})
B0,B1,T1,T0 = np.split(V_in, 4)
plt.add_mesh(T0, (F_in), shading={"wireframe": True})
plt.add_mesh(T1, (F_in), shading={"wireframe": True})

In [ ]:
vols = igl.volume(V_msh, T_msh)
# B0,B1,T1,T0 = np.split(Vs,4)
np.median(vols)
T_boundary = igl.boundary_facets(T_msh)
components = igl.face_components(T_boundary)
p = mp.plot(V_msh, T_boundary[(components == -1), :], shading={"wireframe": True})
p.add_mesh(V_msh, T_msh[vols<1e-9], c=np.ones(3)/3, shading={"wireframe": True})
# p.add_edges(V_msh, Geometry.f2e(T_msh), shading={"wireframe": True})

In [ ]:
p = mp.plot(V_msh_BFS, np.array([[32561, 13493, 17317, 13793]]), shading={"wireframe": True})
# Clipping
F_mask = np.zeros(F.shape[0])
xCoord = V[:, 0]
yCoord = V[:, 1]
zCoord = V[:, 2]
xThres_max = (xCoord.max() - xCoord.min()) * 0.12 + xCoord.min()
xThres_min = (xCoord.max() - xCoord.min()) * 0.05 + xCoord.min()
yThres_max = (yCoord.max() - yCoord.min()) * 0.3 + yCoord.min()
yThres_min = (yCoord.max() - yCoord.min()) * 0.25 + yCoord.min()
zThres_max = (zCoord.max() - zCoord.min()) * 0.85 + zCoord.min()
zThres_min = (zCoord.max() - zCoord.min()) * 0.6 + zCoord.min()
for i in range(int(F.shape[0]/4), int(F.shape[0]/4*3)):
    if ((V[F[i, 0], 0] < xThres_max) or (V[F[i, 1], 0] < xThres_max) or (V[F[i, 2], 0] < xThres_max)) and \
       ((V[F[i, 0], 1] < yThres_max) or (V[F[i, 1], 1] < yThres_max) or (V[F[i, 2], 1] < yThres_max)) and \
       ((V[F[i, 0], 0] > xThres_min) or (V[F[i, 1], 0] > xThres_min) or (V[F[i, 2], 0] > xThres_min)) and \
       ((V[F[i, 0], 1] > yThres_min) or (V[F[i, 1], 1] > yThres_min) or (V[F[i, 2], 1] > yThres_min)) and \
       ((V[F[i, 0], 2] > zThres_min) or (V[F[i, 1], 2] > zThres_min) or (V[F[i, 2], 2] > zThres_min)) and \
       ((V[F[i, 0], 2] < zThres_max) or (V[F[i, 1], 2] < zThres_max) or (V[F[i, 2], 2] < zThres_max)):
        F_mask[i] = True
F_mask = np.array(F_mask, dtype=bool)

colors = np.array([[1, 2, 3, 4]])
colors = np.tile(colors, (int(F.shape[0]/4), 1))
colors = colors.flatten('F')
p.add_mesh(V, F[F_mask, :], c=colors[F_mask], shading={"wireframe": True})

In [ ]:
# boundary_facets
F_bound = igl.boundary_facets(T_msh)
components = igl.face_components(F_bound)

plt = mp.plot(V_msh, F_bound[components == 0, :], shading={"wireframe": True})
# plt.add_edges(V, Geometry.f2e(F))

In [ ]:
# boundary_facets (clip)
F_bound = igl.boundary_facets(T_msh)
components = igl.face_components(F_bound)

N = F_bound.shape[0]
mask = np.zeros((N))
xCoord = V_msh[:, 0]
xThres = (xCoord.max() + xCoord.min()) / 2.0
for i in range(N):
    x_mean = (V_msh[F_bound[i, 0], 0] + V_msh[F_bound[i, 1], 0] + V_msh[F_bound[i, 2], 0]) / 3.0
    mask[i] = (x_mean < xThres) & (components[i] < 57)
mask = np.array(mask, dtype=bool)

plt = mp.plot(V_msh, F_bound[mask, :], shading={"wireframe": True})


In [ ]:
# boundary_facets
T_msh_temp = T_msh[(label == 8) | (label == 9), :]
Visual.Explode(V_msh, T_msh_temp, 0.25)
#plt = mp.plot(V_msh, F_bound[c == 0, :], shading={"wireframe": True})
#plt.add_mesh(V_msh, F_bound[c == 1, :])

In [ ]:
F_bound[components == 2, :]

In [ ]:
testArr = np.array([5787, 81, 52, 5788])
M = T_msh.shape[0]
for i in range(M):
    if (T_msh[i, 1] in testArr) and (T_msh[i, 2] in testArr) and (T_msh[i, 3] in testArr) :
        print(i)
        print(T_msh[i, :])
        print(label[i])
        break
print("done")